name: keking/kkfileview-base
# 添加 workflow_dispatch 事件以支持手动触发
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # 允许手动触发工作流
    inputs: # 定义输入参数（可选）
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
    - name: Log in to Docker Hub
      run: echo qiuxia@1990 | docker login -u qiuxia_echo@163.com --pa
    - name: Build the Docker image
      run: |
        IMAGE_TAG=${{ github.event.inputs.tag }}
        docker build -t keking/kkfileview-base:$IMAGE_TAG -f docker/kkfileview-base/Dockerfile .
   
